language: csharp
solution: library-system.sln
install:
  - nuget library-system.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release library-system.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./library.service.tests/bin/Release/library.service.tests.dll
